url: http://naomijoseph.me
baseurl: 

# Site Settings
title: Naomi Joseph
description: "IT'S NICE TO MEET YOU"
keywords: "theatre, performace, writing"
email: naomi.joseph1@hotmail.co.uk
google-tracking-id: UA-113923707-1

# Career Settings
# Default career thumbnail image.
career-img: "img/me.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]

career-title: Things I've Done

about: Naomi Joseph is a theatre-maker, performer, writer and creative 👋 <br><br>Naomi has worked with many key players within the theatre industry, either as part of a cast or creative team or as a sole developer. Naomi's recent productions include companion pieces Motherland (for theatre) and Criteria (a TEAfilms production). Check out Naomi's body of work below <br><br>🤓👇
