url: http://naomijoseph.me
baseurl: 

# Site Settings
title: Naomi Joseph
description: "IT'S NICE TO MEET YOU"
keywords: "theatre, performace, writing"
email: naomi.joseph1@hotmail.co.uk
google-tracking-id: UA-113923707-1

# Career Settings
# Default career thumbnail image.
career-img: "img/me.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]

career-title: Things I've Done

about: My work explores the vulnerabilities of the human condition grief, loneliness, and social isolation and their effects on individual cultural identity. My work embraces their presence everyday life against the backdrop of a society that wants us to carry these burdens but not communicate them. <br><br> Warning. My work contains dark humour and equal doses of empathy and shade. <br><br> I work across platforms and beyond expectations of the brown, female creative. Check out my body of work below <br><br>🤓👇
